services:
  db:
    image: postgres:18
    container_name: court-booking-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_TEST_DB: ${POSTGRES_TEST_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
      - ./db:/docker-entrypoint-initdb.d
    shm_size: 128mb
  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    container_name: court-booking-swagger
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/docs/openapi.yml
    volumes:
      - ./docs/openapi.yml:/docs/openapi.yml

volumes:
  db-data:
